version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.4-apache
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./public:/var/www/html
      - ./docker-php-errors.ini:/usr/local/etc/php/conf.d/docker-php-errors.ini
    restart: unless-stopped

  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 2AraeHnRkwbEFD5Gm6cp
      MYSQL_DATABASE: propeteer_app_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: securepassword
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 2AraeHnRkwbEFD5Gm6cp
    restart: unless-stopped