services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-propeteer-web:latest
    ports:
      - "80:80"
    volumes:
      # Mount entire project → container sees public/, src/, tests/, vendor/, etc.
      - ./:/var/www/html:cached
      # your custom php.ini settings
      - ./docker-php-errors.ini:/usr/local/etc/php/conf.d/docker-php-errors.ini
    depends_on:
      - db

  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootStrongPass123
      MYSQL_DATABASE: propeteer_app_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: securepassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"   # expose for host-based tools if you need

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootStrongPass123

volumes:
  mysql_data:
